version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: las_vegas_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: las_vegas_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_app:
    build: .
    container_name: las_vegas_flask
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "main.py"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "5000"
      FLASK_DEBUG: "1"
      DATABASE_URL: "postgresql://myuser:mypassword@db/las_vegas_db"
    volumes:
      - ./app:/app
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]

  cron_jobs:
    build: .
    container_name: cron_jobs
    restart: always
    depends_on:
      - db
    command: ["python", "scheduled_tasks.py"]

volumes:
  pgdata:
    external: true