"""Extend Recommendation model with description, event_date, venue

Revision ID: 9fec83a6e95c
Revises: 34f770222d89
Create Date: 2025-02-14 03:43:58.394948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fec83a6e95c'
down_revision = '34f770222d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('venue', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_column('venue')
        batch_op.drop_column('event_date')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
